spring:
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis

app:
  jms:
    destination-name: inn.perception.provision.reply
    routing-type: ANYCAST
    producer-name: perceptionProvisionApp
    reply-user: automationPillar2App
